-- MySQL Script generated by MySQL Workbench
-- Sun Jun 25 20:59:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema GraduationProject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GraduationProject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GraduationProject` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `GraduationProject` ;

-- -----------------------------------------------------
-- Table `GraduationProject`.`airline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GraduationProject`.`airline` (
  `AL_id` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `AL_name` VARCHAR(40) NULL DEFAULT NULL,
  `AL_three_letter_code` INT NULL DEFAULT NULL,
  `AL_phone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`AL_id`),
  UNIQUE INDEX `AL_three_letter_code` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_2` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_3` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_4` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_5` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_6` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_7` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_8` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_9` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_10` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_11` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_12` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_13` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_14` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_15` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_16` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_17` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_18` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_19` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_20` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_21` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_22` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_23` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_24` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_25` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_26` (`AL_three_letter_code` ASC) VISIBLE,
  UNIQUE INDEX `AL_three_letter_code_27` (`AL_three_letter_code` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GraduationProject`.`airports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GraduationProject`.`airports` (
  `AP_id` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `AP_name` VARCHAR(40) NULL DEFAULT NULL,
  `AP_city` VARCHAR(20) NULL DEFAULT NULL,
  `AP_state` VARCHAR(20) NULL DEFAULT NULL,
  `AP_country` VARCHAR(20) NULL DEFAULT NULL,
  `AP_phone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`AP_id`),
  UNIQUE INDEX `AP_name` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_2` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_3` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_4` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_5` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_6` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_7` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_8` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_9` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_10` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_11` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_12` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_13` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_14` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_15` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_16` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_17` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_18` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_19` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_20` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_21` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_22` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_23` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_24` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_25` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_26` (`AP_name` ASC) VISIBLE,
  UNIQUE INDEX `AP_name_27` (`AP_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GraduationProject`.`airport_line`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GraduationProject`.`airport_line` (
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `airportAPId` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `airlineALId` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  PRIMARY KEY (`airportAPId`, `airlineALId`),
  INDEX `airlineALId` (`airlineALId` ASC) VISIBLE,
  CONSTRAINT `airport_line_ibfk_1`
    FOREIGN KEY (`airportAPId`)
    REFERENCES `GraduationProject`.`airports` (`AP_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `airport_line_ibfk_2`
    FOREIGN KEY (`airlineALId`)
    REFERENCES `GraduationProject`.`airline` (`AL_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GraduationProject`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GraduationProject`.`clients` (
  `id` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `birth` DATE NULL DEFAULT NULL,
  `Fname` VARCHAR(45) NULL DEFAULT NULL,
  `Mname` VARCHAR(45) NULL DEFAULT NULL,
  `Lname` VARCHAR(45) NULL DEFAULT NULL,
  `country` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `gender` VARCHAR(45) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GraduationProject`.`biometric_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GraduationProject`.`biometric_data` (
  `id` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `face` BLOB NULL DEFAULT NULL,
  `finger` BLOB NULL DEFAULT NULL,
  `iris` BLOB NULL DEFAULT NULL,
  `clientId` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `clientId` (`clientId` ASC) VISIBLE,
  CONSTRAINT `biometric_data_ibfk_1`
    FOREIGN KEY (`clientId`)
    REFERENCES `GraduationProject`.`clients` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GraduationProject`.`types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GraduationProject`.`types` (
  `flight_type` VARCHAR(10) NOT NULL,
  `no_of_economical_seats` INT NULL DEFAULT NULL,
  `no_of_business_seats` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`flight_type`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GraduationProject`.`flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GraduationProject`.`flights` (
  `id` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `flight_number` VARCHAR(255) NOT NULL,
  `take_off_time` TIME NULL DEFAULT NULL,
  `take_off_date` DATE NULL DEFAULT NULL,
  `status` VARCHAR(20) NULL DEFAULT NULL,
  `duration` TIME NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `airlineALId` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `no_of_stops` INT NULL DEFAULT NULL,
  `typeFlightType` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `flight_number` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_2` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_3` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_4` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_5` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_6` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_7` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_8` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_9` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_10` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_11` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_12` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_13` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_14` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_15` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_16` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_17` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_18` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_19` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_20` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_21` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_22` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_23` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_24` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_25` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_26` (`flight_number` ASC) VISIBLE,
  UNIQUE INDEX `flight_number_27` (`flight_number` ASC) VISIBLE,
  INDEX `airlineALId` (`airlineALId` ASC) VISIBLE,
  INDEX `typeFlightType` (`typeFlightType` ASC) VISIBLE,
  CONSTRAINT `flights_ibfk_49`
    FOREIGN KEY (`airlineALId`)
    REFERENCES `GraduationProject`.`airline` (`AL_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `flights_ibfk_50`
    FOREIGN KEY (`typeFlightType`)
    REFERENCES `GraduationProject`.`types` (`flight_type`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GraduationProject`.`class_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GraduationProject`.`class_details` (
  `class_details_id` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `class` VARCHAR(10) NOT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `weight_limit` DOUBLE NULL DEFAULT NULL,
  `extra_luggage_price` DOUBLE NULL DEFAULT NULL,
  `flightId` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`class_details_id`),
  INDEX `flightId` (`flightId` ASC) VISIBLE,
  CONSTRAINT `class_details_ibfk_1`
    FOREIGN KEY (`flightId`)
    REFERENCES `GraduationProject`.`flights` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GraduationProject`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GraduationProject`.`employees` (
  `SSN` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `Fname` VARCHAR(45) NULL DEFAULT NULL,
  `Lname` VARCHAR(45) NULL DEFAULT NULL,
  `Mname` VARCHAR(45) NULL DEFAULT NULL,
  `gender` VARCHAR(10) NULL DEFAULT NULL,
  `job_title` VARCHAR(20) NULL DEFAULT NULL,
  `address` VARCHAR(20) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `salary` DOUBLE NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `sup_ssn` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `airportAPId` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `birth` DATETIME NULL DEFAULT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`SSN`),
  INDEX `sup_ssn` (`sup_ssn` ASC) VISIBLE,
  INDEX `airportAPId` (`airportAPId` ASC) VISIBLE,
  CONSTRAINT `employees_ibfk_51`
    FOREIGN KEY (`sup_ssn`)
    REFERENCES `GraduationProject`.`employees` (`SSN`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `employees_ibfk_52`
    FOREIGN KEY (`airportAPId`)
    REFERENCES `GraduationProject`.`airports` (`AP_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GraduationProject`.`client_employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GraduationProject`.`client_employee` (
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `employeeSSN` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `clientId` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  PRIMARY KEY (`employeeSSN`, `clientId`),
  INDEX `clientId` (`clientId` ASC) VISIBLE,
  CONSTRAINT `client_employee_ibfk_1`
    FOREIGN KEY (`employeeSSN`)
    REFERENCES `GraduationProject`.`employees` (`SSN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `client_employee_ibfk_2`
    FOREIGN KEY (`clientId`)
    REFERENCES `GraduationProject`.`clients` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GraduationProject`.`client_passport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GraduationProject`.`client_passport` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `passport` VARCHAR(50) NOT NULL,
  `clientId` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `clientId` (`clientId` ASC) VISIBLE,
  CONSTRAINT `client_passport_ibfk_1`
    FOREIGN KEY (`clientId`)
    REFERENCES `GraduationProject`.`clients` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GraduationProject`.`client_phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GraduationProject`.`client_phone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(20) NOT NULL,
  `clientId` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `clientId` (`clientId` ASC) VISIBLE,
  CONSTRAINT `client_phone_ibfk_1`
    FOREIGN KEY (`clientId`)
    REFERENCES `GraduationProject`.`clients` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GraduationProject`.`flightAirports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GraduationProject`.`flightAirports` (
  `airportTo` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `flightId` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `airportFrom` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  PRIMARY KEY (`flightId`, `airportFrom`),
  INDEX `airportFrom` (`airportFrom` ASC) VISIBLE,
  CONSTRAINT `flightAirports_ibfk_1`
    FOREIGN KEY (`flightId`)
    REFERENCES `GraduationProject`.`flights` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `flightAirports_ibfk_2`
    FOREIGN KEY (`airportFrom`)
    REFERENCES `GraduationProject`.`airports` (`AP_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GraduationProject`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GraduationProject`.`payments` (
  `card_number` VARCHAR(16) NOT NULL,
  `card_holder_name` VARCHAR(50) NULL DEFAULT NULL,
  `card_expiry_date` DATE NULL DEFAULT NULL,
  `card_cvv` VARCHAR(3) NULL DEFAULT NULL,
  `clientId` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`card_number`),
  INDEX `clientId` (`clientId` ASC) VISIBLE,
  CONSTRAINT `payments_ibfk_1`
    FOREIGN KEY (`clientId`)
    REFERENCES `GraduationProject`.`clients` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GraduationProject`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GraduationProject`.`tickets` (
  `ticket_number` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `time_of_booking` TIME NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `flightId` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `classDetailClassDetailsId` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `clientId` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`ticket_number`),
  INDEX `flightId` (`flightId` ASC) VISIBLE,
  INDEX `classDetailClassDetailsId` (`classDetailClassDetailsId` ASC) VISIBLE,
  INDEX `clientId` (`clientId` ASC) VISIBLE,
  CONSTRAINT `tickets_ibfk_67`
    FOREIGN KEY (`flightId`)
    REFERENCES `GraduationProject`.`flights` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `tickets_ibfk_68`
    FOREIGN KEY (`classDetailClassDetailsId`)
    REFERENCES `GraduationProject`.`class_details` (`class_details_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `tickets_ibfk_69`
    FOREIGN KEY (`clientId`)
    REFERENCES `GraduationProject`.`clients` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GraduationProject`.`seats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GraduationProject`.`seats` (
  `seat_no` VARCHAR(3) NOT NULL,
  `id` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `classDetailClassDetailsId` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `ticketTicketNumber` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `classDetailClassDetailsId` (`classDetailClassDetailsId` ASC) VISIBLE,
  INDEX `ticketTicketNumber` (`ticketTicketNumber` ASC) VISIBLE,
  CONSTRAINT `seats_ibfk_25`
    FOREIGN KEY (`classDetailClassDetailsId`)
    REFERENCES `GraduationProject`.`class_details` (`class_details_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `seats_ibfk_26`
    FOREIGN KEY (`ticketTicketNumber`)
    REFERENCES `GraduationProject`.`tickets` (`ticket_number`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GraduationProject`.`stops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GraduationProject`.`stops` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  `airport_id` CHAR(36) NOT NULL,
  `duration` TIME NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `flightId` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `flightId` (`flightId` ASC) VISIBLE,
  CONSTRAINT `stops_ibfk_1`
    FOREIGN KEY (`flightId`)
    REFERENCES `GraduationProject`.`flights` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GraduationProject`.`ticket_cancels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GraduationProject`.`ticket_cancels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `money_returned` DOUBLE NULL DEFAULT NULL,
  `client_id` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `payment_id` VARCHAR(16) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `client_id` (`client_id` ASC) VISIBLE,
  INDEX `payment_id` (`payment_id` ASC) VISIBLE,
  CONSTRAINT `ticket_cancels_ibfk_51`
    FOREIGN KEY (`client_id`)
    REFERENCES `GraduationProject`.`clients` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `ticket_cancels_ibfk_52`
    FOREIGN KEY (`payment_id`)
    REFERENCES `GraduationProject`.`payments` (`card_number`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
